# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heart-Clock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaMQTT'
  # Pods for Heart-Clock

end

target 'Watch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Watch

end

target 'Watch Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Watch Extension

end
